const std = @import("std");
const ir = @import("ir.zig");
const Allocator = std.mem.Allocator;

pub const CodeGen = struct {
    gpa: Allocator,
    module: *const ir.Module,
    buf: std.ArrayList(u8),

    param_count: u32,
    value_offsets: std.AutoHashMapUnmanaged(ir.Value, i32),
    alloca_offsets: std.AutoHashMapUnmanaged(u32, i32),

    pub fn init(gpa: Allocator, module: *const ir.Module) @This() {
        return .{
            .gpa = gpa,
            .module = module,
            .buf = .empty,
            .param_count = 0,
            .value_offsets = .{},
            .alloca_offsets = .{},
        };
    }

    pub fn deinit(self: *@This()) void {
        self.buf.deinit(self.gpa);
        self.value_offsets.deinit(self.gpa);
        self.alloca_offsets.deinit(self.gpa);
    }

    fn emit(self: *@This(), comptime fmt: []const u8, args: anytype) !void {
        try self.buf.print(self.gpa, fmt, args);
    }

    fn emitStr(self: *@This(), s: []const u8) !void {
        try self.buf.appendSlice(self.gpa, s);
    }

    pub fn emitModule(self: *@This()) !void {
        try self.emitStr(
            \\; Generated by Tungsten codegen
            \\; Target: x86-64 Windows (NASM)
            \\
            \\bits 64
            \\default rel
            \\
            \\section .text
            \\
        );

        for (self.module.functions.items) |*func| {
            try self.emitFunction(func);
            try self.emitStr("\n");
        }
    }

    fn emitFunction(self: *@This(), func: *const ir.Function) !void {
        self.value_offsets.clearRetainingCapacity();
        self.alloca_offsets.clearRetainingCapacity();
        self.param_count = func.param_count;

        const name = self.module.strings.get(func.name);

        try self.emit("    global _{s}\n", .{name});
        try self.emit("_{s}:\n", .{name});

        try self.emitStr(
            \\    push    rbp
            \\    mov     rbp, rsp
        );

        var value_slots: u32 = self.param_count;
        var alloca_data_slots: u32 = 0;
        for (func.instructions.items) |inst| {
            if (inst.producesValue()) value_slots += 1;
            if (inst.opcode == .alloca) alloca_data_slots += 1;
        }

        const raw_size: u32 = 32 + (value_slots + alloca_data_slots) * 8;
        const frame_size: u32 = (raw_size + 15) & ~@as(u32, 15);

        if (frame_size > 0) {
            try self.emit("\n    sub     rsp, {d}\n", .{frame_size});
        }

        var offset: i32 = 0;

        {
            var i: u32 = 0;
            while (i < self.param_count) : (i += 1) {
                offset -= 8;
                try self.value_offsets.put(self.gpa, @enumFromInt(i), offset);
            }
        }

        {
            var i: u32 = 0;
            while (i < @as(u32, @intCast(func.instructions.items.len))) : (i += 1) {
                const inst = func.instructions.items[i];
                const value_idx = self.param_count + i;

                if (inst.opcode == .alloca) {
                    offset -= 8;
                    const data_off = offset;
                    offset -= 8;
                    try self.value_offsets.put(self.gpa, @enumFromInt(value_idx), offset);
                    try self.alloca_offsets.put(self.gpa, i, data_off);
                } else if (inst.producesValue()) {
                    offset -= 8;
                    try self.value_offsets.put(self.gpa, @enumFromInt(value_idx), offset);
                }
            }
        }

        const reg_names = [_][]const u8{ "rcx", "rdx", "r8", "r9" };
        {
            var i: u32 = 0;
            while (i < self.param_count and i < 4) : (i += 1) {
                const off = self.value_offsets.get(@enumFromInt(i)).?;
                try self.emit("\n    mov     [rbp{d}], {s}\n", .{ off, reg_names[i] });
            }
        }

        for (func.blocks.items, 0..) |block, block_idx| {
            try self.emit("\n.Lbb{d}:\n", .{block_idx});

            const start = @intFromEnum(block.first_inst);
            var rel: u32 = 0;
            while (rel < block.inst_count) : (rel += 1) {
                const inst = func.instructions.items[start + rel];
                const is_last = rel == block.inst_count - 1;

                if (is_last and (inst.opcode == .br or inst.opcode == .cond_br or inst.opcode == .ret)) {
                    try self.emitControlFlow(func, inst, block_idx);
                } else {
                    try self.emitInstruction(func, inst, start + rel);
                }
            }
        }
    }

    fn emitInstruction(self: *@This(), func: *const ir.Function, inst: ir.Instruction, inst_idx: u32) !void {
        const value_idx = self.param_count + inst_idx;
        const ops = func.getOperands(inst.operands);

        switch (inst.opcode) {
            .add, .sub, .mul, .and_op, .or_op, .xor_op => |op| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                const mn = switch (op) {
                    .add => "add",
                    .sub => "sub",
                    .mul => "imul",
                    .and_op => "and",
                    .or_op => "or",
                    .xor_op => "xor",
                    else => unreachable,
                };
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                try self.emit("    {s}     rax, [rbp{d}]\n", .{ mn, b });
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .sdiv, .udiv => |op| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                if (op == .sdiv) {
                    try self.emitStr("    cqo\n");
                } else {
                    try self.emitStr("    xor     edx, edx\n");
                }
                try self.emit("    {s}     qword [rbp{d}]\n", .{ if (op == .sdiv) "idiv" else "div", b });
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .shl, .shr => |op| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                try self.emit("    mov     cl, byte [rbp{d}]\n", .{b});
                try self.emit("    {s}     rax, cl\n", .{if (op == .shl) "shl" else "shr"});
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .icmp_eq, .icmp_ne, .icmp_slt, .icmp_sle, .icmp_sgt, .icmp_sge, .icmp_ult, .icmp_ule, .icmp_ugt, .icmp_uge => |cond| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                const sc = switch (cond) {
                    .icmp_eq => "sete",
                    .icmp_ne => "setne",
                    .icmp_slt => "setl",
                    .icmp_sle => "setle",
                    .icmp_sgt => "setg",
                    .icmp_sge => "setge",
                    .icmp_ult => "setb",
                    .icmp_ule => "setbe",
                    .icmp_ugt => "seta",
                    .icmp_uge => "setae",
                    else => unreachable,
                };
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                try self.emit("    cmp     rax, [rbp{d}]\n", .{b});
                try self.emit("    {s}     al\n", .{sc});
                try self.emitStr("    movzx   eax, al\n");
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .alloca => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const data_off = self.alloca_offsets.get(inst_idx).?;
                try self.emit("    lea     rax, [rbp{d}]\n", .{data_off});
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .load => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const ptr = self.value_offsets.get(@enumFromInt(ops[0])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{ptr});
                try self.emitStr("    mov     rax, [rax]\n");
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .store => {
                const ptr = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const val = self.value_offsets.get(@enumFromInt(ops[1])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{ptr});
                try self.emit("    mov     rdx, [rbp{d}]\n", .{val});
                try self.emitStr("    mov     [rax], rdx\n");
            },

            .call => {
                const target_func = &self.module.functions.items[ops[0]];
                const target_name = self.module.strings.get(target_func.name);
                const arg_count: u32 = @intCast(ops.len - 1);

                const reg_args = [_][]const u8{ "rcx", "rdx", "r8", "r9" };
                const num_reg_args: u32 = @min(arg_count, 4);
                const num_stack_args: u32 = if (arg_count > 4) arg_count - 4 else 0;

                var extra_stack: u32 = 0;
                if (num_stack_args > 0) {
                    extra_stack = num_stack_args * 8;
                    if (num_stack_args % 2 != 0) {
                        extra_stack += 8;
                    }
                }

                if (extra_stack > 0) {
                    try self.emit("    sub     rsp, {d}\n", .{extra_stack});
                }

                {
                    var i: u32 = 0;
                    while (i < num_reg_args) : (i += 1) {
                        const arg_off = self.value_offsets.get(@enumFromInt(ops[1 + i])).?;
                        try self.emit("    mov     {s}, [rbp{d}]\n", .{ reg_args[i], arg_off });
                    }
                }

                {
                    var i: u32 = arg_count;
                    while (i > 4) {
                        i -= 1;
                        const arg_off = self.value_offsets.get(@enumFromInt(ops[1 + i])).?;
                        const stack_pos: i32 = 32 + @as(i32, @intCast(i - 4)) * 8;
                        try self.emit("    mov     rax, [rbp{d}]\n", .{arg_off});
                        try self.emit("    mov     [rsp{d}], rax\n", .{stack_pos});
                    }
                }

                try self.emit("    call    _{s}\n", .{target_name});

                if (extra_stack > 0) {
                    try self.emit("    add     rsp, {d}\n", .{extra_stack});
                }

                if (inst.producesValue()) {
                    const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                    try self.emit("    mov     [rbp{d}], rax\n", .{r});
                }
            },

            .phi => {
                try self.emitStr("    ; phi (resolved at branch site)\n");
            },

            .br, .cond_br, .ret => unreachable,
        }
    }

    fn emitControlFlow(
        self: *@This(),
        func: *const ir.Function,
        inst: ir.Instruction,
        current_block_idx: usize,
    ) !void {
        const ops = func.getOperands(inst.operands);

        switch (inst.opcode) {
            .br => {
                const target_idx = ops[0];
                try self.emitPhiResolution(func, current_block_idx, target_idx);
                try self.emit("    jmp     .Lbb{d}\n", .{target_idx});
            },
            .cond_br => {
                const cond_off = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const true_idx = ops[1];
                const false_idx = ops[2];

                try self.emitPhiResolution(func, current_block_idx, true_idx);
                try self.emitPhiResolution(func, current_block_idx, false_idx);

                try self.emit("    cmp     qword [rbp{d}], 0\n", .{cond_off});
                try self.emit("    je      .Lbb{d}\n", .{false_idx});
                try self.emit("    jmp     .Lbb{d}\n", .{true_idx});
            },
            .ret => {
                const val_off = self.value_offsets.get(@enumFromInt(ops[0])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{val_off});
                try self.emitStr(
                    \\    leave
                    \\    ret
                );
            },
            else => unreachable,
        }
    }

    fn emitPhiResolution(
        self: *@This(),
        func: *const ir.Function,
        source_block_idx: usize,
        target_block_idx: u32,
    ) !void {
        const target_block = func.blocks.items[target_block_idx];
        const start = @intFromEnum(target_block.first_inst);

        for (func.instructions.items[start..][0..target_block.inst_count], 0..) |inst, rel_idx| {
            if (inst.opcode != .phi) break;

            const phi_inst_idx = start + @as(u32, @intCast(rel_idx));
            const phi_value_idx = self.param_count + phi_inst_idx;
            const phi_offset = self.value_offsets.get(@enumFromInt(phi_value_idx)).?;

            const ops = func.getOperands(inst.operands);
            var i: u32 = 0;
            while (i + 1 < ops.len) : (i += 2) {
                if (ops[i + 1] == source_block_idx) {
                    const incoming_off = self.value_offsets.get(@enumFromInt(ops[i])).?;
                    try self.emit("    mov     rax, [rbp{d}]\n", .{incoming_off});
                    try self.emit("    mov     [rbp{d}], rax\n", .{phi_offset});
                    break;
                }
            }
        }
    }
};
